clicon/clixon

etc/Makefile.in

Remove clixonrc on the right target, uninstall, instead of doing that on install-include

Do not remove clixonrc on install-include

---

configure
configure.ac
include/clixon_config.h.in
lib/src/clixon_options.c

Add config option to set a default config file path. If
none given, the default config file path is /etc/clixon.xml.
This will allow running apps without necessarily having
to use -f argument to specify config file.

Use default config file when none is provided

---

configure
configure.ac

Include '=FILE' at the end to make correct usage clearer

Augment help text for --with-configfile

---

configure
configure.ac

Instead of hardcode default config to /etc/clixon.xml, make it to
respect sysconfdir variable. Since autoconf doesn't expand variables on
header substitution it would end up being defined on clixon_config.h as
"${prefix}/etc/clixon.xml" what makes no sense for the header file.
Use eval to expand ${sysconfdir} and make .h file to be defined with
final directory name.

Make default config to respect sysconfdir

---

Makefile.in
apps/backend/Makefile.in
apps/cli/Makefile.in
apps/netconf/Makefile.in
apps/restconf/Makefile.in
datastore/Makefile.in
datastore/keyvalue/Makefile.in
datastore/text/Makefile.in
etc/Makefile.in
example/Makefile.in
lib/clixon/Makefile.in
lib/src/Makefile.in
yang/Makefile.in

- Use 0755 for directories
- Use 0644 for libraries, includes and shared files
- Use -s (strip) parameter when installing binaries and libraries

Improve permissions and strip binaries

---

apps/backend/clixon_backend_handle.c
apps/backend/clixon_backend_transaction.c
apps/restconf/restconf_main.c
apps/restconf/restconf_methods.c

this change enables patchless compilation of clixon on FreeBSD

include limits.h for non-Linux compatibility

---

apps/restconf/Makefile.in

- Use 0755 for directories
- Use 0644 for libraries, includes and shared files
- Use -s (strip) parameter when installing binaries and libraries

Improve permissions and strip binaries (part 2)

---

util/Makefile.in

This affects installations where the libraries are installed outside
the normal library search paths (e.g. FreeBSD puts ports libraries
in /usr/local/lib by default, which is not on the default lib path)

Makefile in util directory didn't use LDFLAGS when building binaries

---

.gitignore
apps/netconf/netconf_main.c
lib/clixon/clixon_plugin.h
lib/clixon/clixon_yang.h
lib/src/clixon_yang.c

this pull request supersedes pull request #55 
use ETIMEDOUT rather than ETIME - this seems more the intent of its
usage here and it compiles under FreeBSD & Linux.
in yang_spec_parse_file() the function basename() is not declared,
the declaration is in libgen.h, so include it. also basename() takes
char * for its argument not const char *, yang_spec_parse_file()
has to be changed to char *filename to compile w/o warnings
these changes have been checked under both Linux and FreeBSD, merging them would simplify the FreeBSD port and remove warnings from both FreeBSD and Linux

FreeBSD compatibility & pedanticism patches 

---

Makefile.in

should install include files with all the other stuff with 'make install' 
In DEB or RPM packages they have the concept of dev and user packages - this can be handled in the package creation scripts so should not break anything there.
Plus, this makes the FreeBSD port easier to do...

Install include files within include target

---

apps/backend/backend_commit.c

when using the -q switch of clixon_backend (upgrade & dump) - sort the XML before dumping it to guarantee a consistent order in the output.

sort the XML before dumping when using -q switch

---

example/main/example_backend.c

The `xmldb_put` is failing due to the `x_spec` field not being set on the xml tree (`xt`) due to no yang spec being passed to the `clixon_xml_parse_string` function.

Fixed example_reset function

---

lib/src/clixon_xml_map.c

this function would never traverse up an XML tree from a node that
was not bound to a YANG model. this prevents the function from
working in some cases where it could.

make xml2xpath1() less picky

---

lib/src/clixon_xml_sort.c

Search key values might contain xml meta-characters. These break
clixon_xml_parse_string() unless properly encoded.

Encode xpath select values with yang

---

apps/netconf/netconf_rpc.c

The "filter" node was not detected when an a namespace was used. The fix is similar to https://github.com/clicon/clixon/commit/d045e8abcec2699ac363947b0fe6061fab5794ba and related to bug #154 #143

Fixed filter-namespace not recognized correctly

---

lib/src/clixon_datastore_read.c

The cached xml version might be missing the yang information. This
breaks netconf validation of the running database:
yangcli admin@192.168.0.1> validate source=startup
RPC Error Reply 3 for session 3:
rpc-reply {
rpc-error {
error-type application
error-tag operation-failed
error-severity error
error-message 'No spec found radio-dn'
}
}
Make sure that the cached database respects the yb parameter.

datastore_read: bind yang when reading from cache

---

configure
configure.ac

When using "./configure --without-restconfig" the variables "WWWUSER" and "WWWDIR" are not defined, leading to a build failure. This change simply sets those variables to an empty string. Not sure if this is the correct way of doing it tho!

fix: Build breaks when using "--without-restconfig"

---

apps/cli/cli_generate.c

Currently the yang extension: cl:autocli-op hide; only work with list and leaf type.
This patch can make container type also support cl:autocli-op.

yang container add support for cl:autocli-op

---

lib/src/clixon_log.c

localtime isn't thread-safe and therefore, it caused crashes in our system, in certain cases. localtime_r is thread-safe.

change localtime to localtime_r which is a thread-safe function

---

lib/src/clixon_file.c

While porting clixon to the RTOS Blackberry QNX there was memory corruption while reading the yang models from the disk.
Debugging led to the function `clicon_file_dirent` in `clixon_file.c` in which the `struct dirent` is copied into an array.
According to the UNIX `struct dirent` [documentation](https://man7.org/linux/man-pages/man0/dirent.h.0p.html):
>  The name of an array of char of an unspecified size should not be
>  used as an lvalue. Use of:
>
>         sizeof(d_name)
>
>  is incorrect; use:
>
>         strlen(d_name)
>
>  instead.
I adjusted the memory allocation to take the `strlen(dent->d_name)` into account.

Fixed memory allocation for `struct dirent`

---

apps/cli/cli_common.c

Like other programs, diff can and should be located using PATH.
This fixes compare_dbs() on non-FHS systems, like NixOS.

Remove hardcoded path to diff binary

---

apps/netconf/Makefile.in

In commit https://github.com/clicon/clixon/commit/5a875e3152d5647e01f4ed5c3551066273c719a1#diff-4d7a9475650e34ce4598d7562b0d77b9de0d265cc7dac7c5a0bad8451f5fab11 you've replaced the `SH_SUFFIX` variable with a static value of `.so`. This PR is reverting this change.

Fixed SH_SUFFIX

---

configure
configure.ac

Fixing the behavior when using the `--enable-debug` flag -> the `CFLAGS` variable get's overwritten. Also logging out the `LDFLAGS` variable for debugging purposes.

Fixed CFLags for debug mode

---

Makefile.in

Updated the Makefile.in to check if the `id` utility exists on the platform, otherwise skip the root check.

Updated warnroot and checkroot Commands

---

configure
configure.ac

Even though QNX support the sigaction function, it does not support the `SA_RESTART` mode. The additional flag in the configure script allows passing `--without-sigaction` to disable the sigaction logic.

Added --without-sigaction option

---

lib/src/clixon_json_parse.y

Concatenate prefix and name before calling `json_current_new` when cloning.
Solves #268

Append prefix when cloning json node

---

lib/src/clixon_json.c
test/test_restconf_op.sh

Convert int64, uint64 and decimal64 to string in xml to json convertion (regarding to RFC7951):
`A value of the "int64", "uint64", or "decimal64" type is represented
as a JSON string whose content is the lexical representation of the
corresponding YANG type as specified in Sections [9.2.1](https://datatracker.ietf.org/doc/html/rfc7951#section-9.2.1) and [9.3.1](https://datatracker.ietf.org/doc/html/rfc7951#section-9.3.1) of
[[RFC7950](https://datatracker.ietf.org/doc/html/rfc7950)].`

Convert int64, uint64 and decimal64 to string in xml to json

---

doc/FAQ.md

This massive PR fixes the link to the `hello world` example in the FAQ.md.  Other links in the file were checked for correctness.

Update FAQ.md hello world example url

---

apps/cli/cli_plugin.c

* The fflush(f) was added at the end of clicon_parse(...) to push out error messages if stream was buffered;
* Fixed output of some logs in stderr when stdout was selected for error message output;

Error message stucks in stdout buffer

---

apps/snmp/snmp_lib.c
test/test_snmp_union.sh

Support yang type union with are same subtypes with SNMP

Support union with are same subtypes with SNMP

---

config-aux/install-sh
configure
configure.ac
docker/example/Dockerfile
docker/test/Dockerfile
docker/test/Dockerfile.fcgi
docker/test/Dockerfile.native

The main purpose of these commits is to fix build when `CLIGEN_DIR` is set or `--with-cligen=dir` is passed to configure.  Before this change CFLAGS and LDFLAGS were not respecting `$includedir` and `$libdir`

Fix cligen dir

---

configure
configure.ac
include/clixon_config.h.in
include/clixon_custom.h

This PR branch is based on PR #436 and cannot be merged before it.
The idea is to make it possible to change default restconf network namespace as a configure option.  Only 3 last commits belong to this one.

Implement restconf netns default

---

apps/backend/backend_client.c
lib/src/clixon_netconf_monitoring.c
lib/src/clixon_proc.c
lib/src/clixon_stream.c
util/clixon_util_stream.c

Even though a `struct timeval` isn't a particularly large structure, it's a bad practice to pass structures by value as it's inefficient.

Avoid copying timeval onto stack

---

configure
configure.ac

`${datadir}` then expands to some version of `${datarootdir}/...`.

Fix double expansion of ${datadir}

---

configure.ac

Building clixon on FreeBSD requires setting `--with-cligen=${LOCALBASE}`. However, the current implementation of `--with-cligen` mangles the resulting CPPFLAGS and LDFLAGS. This patch un-breaks the `--with-cligen` option. The Clixon 6.4.0 patch for FreeBSD carries this patch locally in order to build successfully.
https://bz-attachments.freebsd.org/attachment.cgi?id=245384

Fix `--with-cligen` build option

---

apps/backend/backend_main.c
apps/restconf/restconf_main_native.c
lib/src/clixon_plugin.c
lib/src/clixon_proc.c
lib/src/clixon_string.c
lib/src/clixon_uid.c
util/clixon_util_path.c

There are calls to `fprintf(stderr, ...);` and `perror(...);` that only are seen if we're running in the foreground, with logging sent to `stdout`.

Cleanup error handling

---

configure
configure.ac

Simplifying the previous "fix --with-cligen build option" so that we don't have to keep using `eval echo $var`.

Avoid additional 'eval echo ...' sequences

---

apps/backend/backend_commit.c

In the transaction that applies plugin's config don't include yang's defaults in the transaction source.

Let restart-plugin RPC pick up on yang's defaults

---

Makefile.in

`util` requires `libbackend.so` to be built first, but that doesn't happen until `apps/backend/` gets built, so capture that dependency.
You can reproduce this in `master` by:
```
% make -j8 all util
```

Fix race condition

---

configure
configure.ac
docker/clixon-dev/Dockerfile
docker/example/Dockerfile
docker/test/Dockerfile
docker/test/Dockerfile.fcgi
docker/test/Dockerfile.native

Adding `-I${INCLUDEDIR}` unconditionally to `CPPFLAGS` will cause the compiler to search the build-host's local headers, which will be disastrous.

Revert PR#457 as it breaks cross-compilation

---

test/test_pagination_expect.exp

Explode string into list of words for `spawn`.

Fix issues with valgrind w/ sudo

---

test/test_pagination_expect.exp

When the paginated output is done, we should see the CLI prompt.

Check for final prompt in pagination

---

lib/clixon/clixon_debug.h
lib/src/clixon_datastore.c
lib/src/clixon_datastore_read.c
lib/src/clixon_debug.c
lib/src/clixon_event.c
lib/src/clixon_nacm.c
lib/src/clixon_proc.c

NACM generates a lot of noise but you rarely need its logging unless you're debugging it specifically.

Add more shades of debug messages

---

lib/clixon/clixon_debug.h
lib/src/clixon_plugin.c

Add separate logging for RPC registration and invocation.

Add RPC-specific debugging

---

apps/snmp/snmp_lib.c
test/test_snmp_get.sh

In the SNMP protocol all tranfered values (bindings) have a defined length. Therefore the octet string does not need a null terminator. If there is one, it is transfered as control character and may confuse SNMP agents like snmp4j. (snmpget shows a "." character at the end what ist not correct.)
Check the result without and with this fix ("." at the end of "Some string value")
```
--> Without this fix:
$ snmpget -v2c -c private localhost SIMPLE-MIB::testAlphaOneConfstring.0
SIMPLE-MIB::testAlphaOneConfstring.0 = STRING: Some string value.
--> With this fix:
$ snmpget -v2c -c private localhost SIMPLE-MIB::testAlphaOneConfstring.0
SIMPLE-MIB::testAlphaOneConfstring.0 = STRING: Some string value
```

Remove null terminator for SNMP octet string

---

lib/clixon/clixon_xml_map.h
lib/src/clixon_xml_map.c

Add new helper functions for reading / writing bits data type. This functions will be required to implement SNMP bits data type support (in separate pull request) later on.
(Part one of splitted previous pull request [491](https://github.com/clicon/clixon/pull/491))

Add helper functions for bits data type

---

apps/restconf/Makefile.in

Setup YACC and LEX via autoconf
On opensuse tumbleweed I had a build error because the wrong lex variant was used without this.
This is the same as in lib/src/Makefile.in

Use yacc and lex as detected by autoconf to build restconf

---

lib/src/clixon_xml_map.c

Generating state for a yang module that has both state and config below a mountpoint fails with an error:
> XML node %s/%s has no corresponding yang specification (Invalid XML or wrong Yang spec
This is because netconf_trymerge() will be called to merge state and config, which will in turn trigger a problem in xml_merge1(). Fix that.

Fix for showing state below mountpoints

---

apps/backend/backend_plugin.c
lib/src/clixon_plugin.c

These are some things I ran into while working in clixon.  They consolidate common code and remove unnecessary stuff, mostly.
There is one thing I think is a bug fix.  If you don't have an exit function for an API, it will not unload the module.  Is that intended?  If so, it should probably be documented.

General fixes for clixon

---

configure
configure.ac

Our crosscompile build / configure task failed because of the openssl check. The reason is that libssl was tested before libcrypto. Without libcrypto, however, libssl cannot be built, which is why the configure task fails. This pull request changes the order in the configure file.
(It also removes all trailing spaces. Due to the previous pull request findings, I have changed my IDE settings so that these are now always removed.)

Check libcrypto before libssl to avoid configure errors

---

apps/snmp/snmp_stream.c

With activated NACM the snmp subagent is not able to read and subscribe the streams. With this pull-request we add the username to the internal netconf request between the snmp subagent and clixon backend

Add username when reading and subscribing streams

---

configure.ac

Do not hardcode /usr/local/etc as the location.

configure.ac: Fix the directory for the config file to use $SYSCONFDIR.

---

apps/backend/backend_plugin.c
lib/clixon/clixon_plugin.h

Hello @olofhagsand 
Following this conversation https://github.com/clicon/clixon/issues/517
Could you pls check if it possible to merge this PR?
Current callback order:
```
Aug 30 05:33:04.906929: Plugin 01: BEGIN
Aug 30 05:33:04.906944: Plugin 02: BEGIN
Aug 30 05:33:04.906947: Plugin 03: BEGIN
Aug 30 05:33:04.906950: Plugin 04: BEGIN
Aug 30 05:33:04.906969: Plugin 01: VALIDATE
Aug 30 05:33:04.906972: Plugin 02: VALIDATE
Aug 30 05:33:04.906974: Plugin 03: VALIDATE
Aug 30 05:33:04.906977: Plugin 04: VALIDATE
Aug 30 05:33:04.906980: Plugin 01: COMPLETE
Aug 30 05:33:04.906982: Plugin 02: COMPLETE
Aug 30 05:33:04.906984: Plugin 03: COMPLETE
Aug 30 05:33:04.906986: Plugin 04: COMPLETE
Aug 30 05:33:04.906995: Plugin 01: COMMIT
Aug 30 05:33:04.906998: Plugin 02: COMMIT
Aug 30 05:33:04.907000: …
```

add revert failed cb

---

apps/backend/backend_client.c
apps/backend/backend_commit.c
apps/backend/backend_plugin.c
example/main/example_backend_nacm.c
lib/clixon/clixon_netconf_lib.h
lib/clixon/clixon_plugin.h
lib/src/clixon_netconf_lib.c
lib/src/clixon_plugin.c
test/test_transaction.sh

Add plugin_rpc_err(), which works something like clixon_err, but it saves error information from a plugin for reporting rpc-errors that need to be returned.
This is an RFC, would this be ok?

Add a way to report rpc-errors from a plugin

---

lib/src/clixon_log.c

In musl libc, valgrind may detect an "Invalid file descriptor" error upon `closelog()` call if the previous `openlog()` call was not passed the `LOG_NDELAY` option and `syslog()` wasn't called afterwards.
musl libc has an issue in this file: https://git.musl-libc.org/cgit/musl/tree/src/misc/syslog.c?id=c47ad25ea3b484e10326f933e927c0bc8cded3da
Namely, in `openlog()`, `__openlog()` which sets `log_fd` is not called immediately if `LOG_NDELAY` option is not used. In this case, `log_fd` is only set upon next `syslog()` call. `closelog()` does not check if `log_fd == 1` and just tries to close `log_fd`, causing `Invalid file descriptor` error which is shown by valgrind.
In my environment, this was causing mem tests to fail in `test_confirmed_commit.sh` with the following diagnostics:
``` …
```

Fix valgrind error upon closelog() when using musl libc

---

lib/clixon/clixon_stream.h
lib/src/clixon_stream.c

Added function for server side with oppportunity to close all opened stream sockets using only name of a stream.

stream: removing all opened sockets for a stream
